### ISSUE TITLE
validation ways

### ISSUE THREAD

**Issue by johnny4young** [addapptables/cli#2]
https://github.com/addapptables/cli/blob/e3b345ea7438554cdd6836a58e90e1577bd032cb/internal/commands/create-project.go#L58

has you consider to use Cobra for validations?, eg:

 Args: func(cmd *cobra.Command, args []string) error {
    if len(args) < 1 {
      return errors.New("requires a color argument")
    }
    if myapp.IsValidColor(args[0]) {
      return nil
    }
    return fmt.Errorf("invalid color specified: %s", args[0])
  },

**Comment by sebastiandelaroche** [comment]
Yes, you're right 
Thank you for the advice 

https://github.com/addapptables/cli/blob/develop/cli/command/new/cmd.go#L20
